CREATE TABLE EMPLOYEE (
	SSN INT PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	DeptNo INT NOT NULL
);

CREATE TABLE PROJECT (
	ProjectNo INT PRIMARY KEY,
	ProjectArea VARCHAR(100) NOT NULL 
);

CREATE TABLE ASSIGNED_TO (
	SSN INT,
	ProjectNo INT,
	PRIMARY KEY (SSN, ProjectNo),
	FOREIGN KEY (SSN) REFERENCES EMPLOYEE (SSN) ON DELETE CASCADE,
	FOREIGN KEy (ProjectNo) REFERENCES PROJECT (ProjectNo) ON DELETE CASCADE
);

SELECT E.SSN FROM EMPLOYEE E, PROJECT P, ASSIGNED_TO A WHERE E.SSN = A.SSN AND P.ProjectNo = A.ProjectNo AND P.ProjectArea LIKE %database%;

SELECT DeptNo, COUNT (SSN) AS NO_OF_EMPLOYEES FROM EMPLOYEE GROUP BY DeptNo;

UPDATE ASSIGNED_TO SET ProjectNo = 20 WHERE SSN = 1;