CREATE TABLE EMPLOYEE (
	SSN INT PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	DeptNO INT NOT NULL
);

CREATE TABLE PROJECT (
	ProjectNo INT PRIMARY KEY,
	ProjectArea VARCHAR(100) NOT NULL 
);

CREATE TABLE ASSIGNED_TO (
	SSN INT,
	ProjectNo INT,
	PRIMARY KEY (SSN, ProjectNo),
	FOREIGN KEY (SSN) REFERENCES EMPLOYEE (SSN) ON DELETE CASCADE,

);

